### ISSUE TITLE
Sweep: Change any reference to upmortem.com domain to haly.ai domain

### ISSUE THREAD

**Issue by nlake44** [UpMortem/slack-bot#60]
<details open>
<summary>Checklist</summary>

- [X] `src/services/api_service.py`
> • Replace 'upmortem.com' with 'haly.ai' in the BASE_URL variable.

- [X] `src/services/slack_service.py`
> • Search for any URLs that are being used to redirect users. If they contain 'upmortem.com', replace it with 'haly.ai'.

- [X] `README.md`
> • Replace any instances of 'upmortem.com' with 'haly.ai'.

- [X] `src/services/openai_service.py`
> • If there are any instances of 'upmortem.com', replace them with 'haly.ai'.

- [ ] `cloudbuild.yml`
> • If there are any instances of 'upmortem.com', replace them with 'haly.ai'.

</details>

**Comment by wwzeng1** [comment]
Hey @nlake44, apologies for the issues. We're migrating our backend and this is causing some bugs. Thank you for your patience and I'll reset your GPT4 ticket count.

**Comment by nlake44** [comment]
Appreciate you guys helping out open source projects!

**Comment by wwzeng1** [comment]
We're going to write a guide on how to self-host sweep with your own openai key
